config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :blogs do
    resources :comments, only: [:create, :destroy]
  end

  root 'welcome#home'

end

app/models/blog.rb
# == Schema Information
#
# Table name: blogs
#
#  created_at :datetime         not null
#  id         :integer          not null, primary key
#  text       :text(65535)
#  title      :string(255)
#  updated_at :datetime         not null
#

class Blog < ActiveRecord::Base
  has_many :comments, dependent: :delete_all
  validates :title, presence: true, length: { minimum: 5 }
  validates :text, presence: true, length: { in: 6..200 }
end

app/models/comment.rb
# -*- SkipSchemaAnnotations
class GoodnessValidator < ActiveModel::Validator
  def validate(record)
    if record.commenter == "Bad"
      record.errors[:base] << "Bad cannot be the name"
    end
  end
end


class Comment < ActiveRecord::Base
  belongs_to :blog
  validates :commenter, presence: true, length: { minimum: 3, message: "commenter should be min 3 in length"}
  validates_each :commenter do |record, attr, value|
    record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
  end
  validates :body, presence: true, length: { in: 6..200 }
  validates_with GoodnessValidator
  before_create do
    puts ">>>>>>>Comment Created!"
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  avatar_content_type    :string(255)
#  avatar_file_name       :string(255)
#  avatar_file_size       :integer
#  avatar_updated_at      :datetime
#  created_at             :datetime         not null
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :string(255)
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  id                     :integer          not null, primary key
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :string(255)
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string(255)
#  sign_in_count          :integer          default(0), not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates_attachment :avatar, size: { in: 0..2000.kilobytes }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:password, :password_confirmation, :current_password, :avatar])
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
    @blogs = Blog.all()
  end

  def new
    @blog = Blog.new
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(get_params())
    if @blog.save
      redirect_to @blog
    else
      render 'new'
    end

  end

  def update
    @blog = Blog.find(params[:id])

    if @blog.update(get_params)
      redirect_to @blog
    else
      render 'edit'
    end
  end

  def show
    @blog = Blog.find(params[:id])
  end

  private
    def get_params
      params.require(:blog).permit(:title, :text)
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :authenticate_user!
  before_action :get_blog,  only: [:edit, :update, :show, :destroy]

  def index
    @q = Blog.ransack(params[:q])
    @blogs = @q.result.paginate(page: params[:page], per_page: 2).order('created_at DESC')
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = Blog.new(get_params())
    if @blog.save
      redirect_to @blog, flash: {message: 'Blog Created Successfully!'}
    else
      render 'new'
    end

  end

  def update
    if @blog.update(get_params)
      redirect_to @blog, flash: {message: 'Blog updated Successfully!'}
    else
      render 'edit'
    end
  end

  def show
    @comment = Comment.new
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, flash: {message: 'Blog destroyed!'}
  end

  private
    def get_params
      params.require(:blog).permit(:title, :text)
    end
    def get_blog
      @blog = Blog.find(params[:id])
    end

    # testing binding of caller gem
    def a
      var = 10
      b
      puts '>>>>>>>>>>>>>>>>>>>>>>>>>>>>>'
      puts var
    end

    def b
      c
    end

    def c
      binding.of_caller(2).eval('var = :hello')
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_blog

  def create
    @comment = @blog.comments.new(comment_params)
    if @blog.save
      redirect_to @blog
    else
      render 'blogs/show'
    end
  end

  def destroy
    @comment = @blog.comments.find(params[:id])
    @comment.destroy
    redirect_to @blog
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
    def get_blog
      @blog = Blog.find(params[:blog_id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
def home
  @current_users = User.all
  render 'welcome/homePage'
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog/edit.html.erb
<h1>Editing Blog</h1>

<%= form_for :blog, url: blog_path(@blog), method: :patch do |f| %>

  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@blog.errors.count, "error") %> prohibited
        this blog from being saved:
      </h2>
      <ul>
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>
<%= link_to 'Back', blog_index_path %>

app/views/blog/index.html.erb
<%= link_to 'New blog', new_blog_path %>
<h1>Listing Blogs</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @blogs.each do |blog| %>
    <tr>
      <td><%= blog.title %></td>
      <td><%= blog.text %></td>
      <td><%= link_to 'Show', blog_path(blog) %></td>
      <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
    </tr>
  <% end %>
</table>

app/views/blog/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @blog.text %>
</p>
<%= link_to 'Edit', edit_blog_path(@blog) %>
<%= link_to 'Back', blog_index_path %>

app/views/blogs/_form.html.haml
= form_for blog do |f|
  - if blog.errors.any?
    #error_explanation
      %h2
        = pluralize(blog.errors.count, "error")
        prohibited
        this blog from being saved:
      %ul
        - blog.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label :title
    %br
    = f.text_field :title
  %p
    = f.label :text
    %br
    = f.text_area :text, size: "60x12"
  %p
    = f.submit

app/views/blogs/edit.html.haml
%h1 Editing Blog
= render 'form', blog: @blog
= link_to 'Back', blogs_path

app/views/blogs/index.html.haml
= link_to 'New blog', new_blog_path
%h1 Listing Blogs
= will_paginate(@blogs, params: {check: 'test'}, style: 'color:red', previous_label: 'back')
= search_form_for @q do |f|
  = f.label 'Title'
  = f.search_field :title_cont

  = f.label :text_start
  = f.search_field :text_start

  = f.label 'Start Date'
  = f.search_field :created_at_gteq

  = f.label 'End Date'
  = f.search_field :created_at_lteq

  = f.submit

%table{:style=>"border: 1px; width: 50%"}
  %tr{style: 'width: 200%'}
    =sort_link(@q, :title, 'Title', default_order: :desc, hide_indicator: true)
    =sort_link(@q, :text, 'Text', default_order: :desc, hide_indicator: true)
    =sort_link(@q, :created_at, 'Date', default_order: :desc, hide_indicator: true)
  - @blogs.each do |blog|
    %tr
      %td= blog.title
      %td= blog.text
      %td= blog.created_at ? blog.created_at.strftime("%I:%M %p, #{blog.created_at.day.ordinalize} %h, %Y") : ''
      %td= link_to 'Show', blog_path(blog)
      %td= link_to 'Edit', edit_blog_path(blog)
      %td= link_to 'Destroy', blog_path(blog), |
          method: :delete,                    |
          data: { confirm: 'Are you sure?' }  |

app/views/blogs/new.html.haml
%h1 New Blog
= render 'form', blog: @blog
= link_to 'Back', blogs_path

app/views/blogs/show.html.haml
%p
  %strong Title:
  = @blog.title
%p
  %strong Text:
  = @blog.text

%h2 Comments
- if @comment && @comment.errors.any?
  #error_explanation
    %h2
      = pluralize(@comment.errors.count, "error")
      prohibited
      this comment from being saved:
    %ul
      - @comment.errors.full_messages.each do |msg|
        %li= msg
= render @blog.comments
%h2 Add a comment:
= render 'comments/form', blog: @blog
= link_to 'Edit', edit_blog_path(@blog)
= link_to 'Back', blogs_path

app/views/comments/_comment.html.haml
- if comment.id
  %p
    %strong Commenter:
    = comment.commenter
  %p
    %strong Comment:
    = comment.body
  %p
    %strong Date:
    = comment.created_at ? (comment.created_at + (5*60).minutes + 30.minutes).strftime("%F %T") : ''
  = link_to 'Delete comment', [comment.blog, comment], |
    method: :delete                                    |

app/views/comments/_form.html.haml
= form_for([blog, blog.comments.build]) do |f|
  %p
    = f.label :commenter
    %br
    = f.text_field :commenter
  %p
    = f.label :body
    %br/
    = f.text_area :body
  %p
    = f.submit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RailsBlog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - flash.each do |name, msg|
      = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
    = render 'devise/logout/logout'
    = yield

app/views/welcome/homePage.html.haml
- if user_signed_in?
  = link_to 'Blogs', blogs_path
- else
  %h1 Users
  %table
    %tr
      %th Id
      %th Email
    - @current_users.each do |user|
      %tr
        %td= user.id
        %td= user.email